### ISSUE TITLE
Timed out after 10 seconds

### ISSUE THREAD

**Issue by InsaniManES** [aluisiora/node-routeros#10]
I tested on my Mikrotik (just connecting):

{
name: "RosException",
errno: "SOCKTMOUT",
message: "Timed out after 10 seconds"
}

I applied to port 8728 but still, it doesn't work.

**Comment by aluisiora** [comment]
RouterOS doesn't keep the connection alive by default, but you can add a `keepalive: true` with the connection options like:

```javascript
const conn = new RouterOSAPI({
    host: "192.168.88.1",
    user: "admin",
    keepalive: true
});
```

Lemme know if that works.

**Comment by InsaniManES** [comment]
Still the same, this is my full code:

var express = require('express');
var app = express();

const RosApi = require("node-routeros").RouterOSAPI;

const RouterOSClient = require('routeros-client').RouterOSClient;

app.get('/:ip', function(req, res){

    console.log(req.params.ip);

    let api = new RouterOSClient({
        host: req.params.ip,
        user: "admin",
        password: "123456",
        keepalive: true
    });
    
    api.connect().then((client) => {
        res.send('You are connected!');    
    }).catch((err) => {
        res.send(err);
    });
});

app.listen(5000,()=>{
    console.log('Listening to port 5000');
});

**Comment by aluisiora** [comment]
I see, have you checked if the api port is open on your firewall? Is it a lan or wan ip you are trying to connect through?

**Comment by InsaniManES** [comment]
wan ip, do I need to configure something to make that work?

**Comment by aluisiora** [comment]
You need to add a firewall rule in the input chain for the 8728 tcp port, otherwise the routerboard will drop the packets.

Also, I assume you made sure that the api service is running, right?

**Comment by InsaniManES** [comment]
Thanks, now it's working!
