### ISSUE TITLE
How to detect RouterOSAPI.stream's end

### ISSUE THREAD

**Issue by andre-luiz-dos-santos** [aluisiora/node-routeros#11]
How to detect when a RouterOSAPI.stream is complete?

I'm testing using the /ip/address/print command.
I was expecting the stream returned from RouterOSAPI.stream to emit either the close or the end event, but neither one is emitted.

**Comment by andre-luiz-dos-santos** [comment]
I can detect it using the `channel` property on the stream object, but TypeScript complains that it's private:

```js
stream.channel.on("close", () => { observer.complete() });
```

```
error TS2341: Property 'channel' is private and only accessible within class 'RStream'.
```

**Comment by aluisiora** [comment]
I see. The idea of a stream in this context is that it never ends, you should define when you wanna close it.

If you are just printing the ip address, use this syntax instead:

```typescript
conn.write("/ip/address/print").then((data) => {
    console.log(data);
});

// or with async/await
const data = await conn.write("/ip/address/print");
console.log(data);
```

Stream is used for things like /tool/torch, or when you use listen or intervals like:
```typescript
conn.stream(['/ip/address/listen'], (error, packet) => {
    console.log(packet);
});
```
In these cases, the stream never stops unless you tell it to.

**Comment by andre-luiz-dos-santos** [comment]
I have a watch function that starts a /listen command, and then runs /print to get all the current records. The idea is to create an RxJS Observable that emits all active PPP connections, and then emits for every account that connects or disconnects.

I want to use RouterOSAPI.stream for the /print command as well, because there may be thousands of records to be received and the link between this program and the RouterOS device may be slow.

**Comment by aluisiora** [comment]
I see, you need to get small chunks of a large dataset from the print command, in that case I'll need to make some adaptations to the code.

Meanwhile, you can add a "// @ts-ignore" above the line that you listen to the channel event.

I had a similar use case but instead I used the data from the "/listen" itself to mutate a previous dataset from a "/print" command, so I don't need to print again to get the current state. I might as well implement such feature within the API to make things easier 😅.

**Comment by aluisiora** [comment]
Added a new method `writeStream` which behaves like the `write` command but it returns an `EventEmitter` object. From it you can listen to `data`, `trap`, `close` and `done` events.

The `done` event only triggers when the data finishes streaming and there was no error.
If a `trap` gets emitted, the `done` will not be emitted. 
The `close` event gets emitted regardless of success or failure.

Example code:
```javascript
const stream = conn.writeStream('/ip/address/print');

stream.on('data', (data) => {
    console.log('got some data!', data);
});

stream.on('trap', (error) => {
    console.log('Got error: ', error.message);
});

stream.on('done', () => {
    console.log('stream finished!');
});

stream.on('close', () => {
    console.log('channel finished, it is now closed!');
});
```

**Comment by andre-luiz-dos-santos** [comment]
How may I close the stream without closing the connection? There is no end or close function on the stream object.

Another option would be to run the RouterOS API /cancel command manually, but I have not found any way to discover the stream tag.

**Comment by aluisiora** [comment]
Oops. Yeah, currently you can't stop it, I'm gonna update it so you can do that, hang tight.

**Comment by aluisiora** [comment]
I've updated the package to `v1.6.0`, now the `writeStream` will return an `RStream` object, the same event from before will still work plus you can call `close()`, `pause()` and `resume()` functions if you want. If you had any typescript declaration to the previouly returned `EventEmitter` class, you might need to update it.

Please, tell me if this update works for you.

**Comment by andre-luiz-dos-santos** [comment]
Worked perfectly. Thank you!
