### ISSUE TITLE
TypeScript's d.ts files are missing

### ISSUE THREAD

**Issue by andre-luiz-dos-santos** [aluisiora/node-routeros#13]
node-routeros does not provide TypeScript's d.ts files starting with version 1.4.4.
I tried installing them from the package `@types/node-routeros`, but that doesn't exist.
Where may I find the TypeScript's d.ts files now?

**Comment by aluisiora** [comment]
I'm terribly sorry, I modified the tsconfig file and didn't include the declaration files. Update to 1.5.2 and let me know if it worked.

**Comment by andre-luiz-dos-santos** [comment]
It's working now. Thank you!
