### ISSUE TITLE
Connection error leaving command promises orphaned

### ISSUE THREAD

**Issue by ZackMattor** [aluisiora/node-routeros#18]
We have a few bad actors in our fleet of routers. We get periodic TCP connection resets from them which cause the connection to throw an error. When this happens any inflight API calls get orphaned - never to resolve or reject. Goofy example is as follows.

```
routeros.on('error', (e) => logger(e));

function doThings() {
  let res = await routeros.write('/systen/resource/print');
  console.log(res.data);
  setTimeout(doThings, 5000);
}

doThings();
```

1. `doThings` gets called
2. `/system/resource/print` gets sent to router
3. Router sends back response
4. data gets logged
5. doThings gets schedules for 5 seconds down the road
6. `doThings` gets called
7. `/system/resource/print` gets sent to router
8. ECONNRESET gets thrown
9. error gets logged
10. promise never gets resolved which means we are waiting forever for `/system/resource/print` and we never proceed

Actual scenario is a bit more complex than this.... but I think this outlines the issue. Currently we have a workaround. But my suggestion would be for all inflight `writes` to reject their promises upon connection error.

**Comment by aluisiora** [comment]
Narrowed down to some stream timeouts that keep running even after disconnecting, working on a fix.

**Comment by aluisiora** [comment]
Trying to find something related to unhandled promises after a disconnection. That'll be harder to reproduce.

UPDATE: Used the code sample from the OP after implementing some changes to the code and disconnecting/shutting down the router by force and it seems to exit normally. Hope that fixes it, will wait for some confirmation.

**Comment by ZackMattor** [comment]
I haven’t tested throughly but we are using the newest releases in production currently and we’re not seeing out fallback hack for this being triggered as often as far as I can tell!
