### ISSUE TITLE
Make the TLS feature work

### ISSUE THREAD

**Issue by aluisiora** [aluisiora/node-routeros#2]
Currently, connecting with SSL via api is not very well tested, need to write tests and make fixes if needed.

**Comment by danlobo** [comment]
Changed some code on Connector.js and had some progress:
Line 86,
from:
`this.socket = new TLSSocket(this.socket, options.tls);`
to:
`this.tls = options.tls`

Line 110,
from:
`this.socket.connect(this.port, this.host);`
to:
```
this.socket.connect(this.port, this.host);
                if (this.tls) {
                    this.tls.socket = this.socket
                    this.socket = tls_1.connect(this.tls)
                }
```
Now the TLS socket starts to communicate, but the connection hangs up, dunno why yet.

Didn't have time to make a PR, but drop me a line if needed.

Thanks,

**Comment by aluisiora** [comment]
Thank you! I'll take a look at your PR, uai sô.

**Comment by danlobo** [comment]
Would you mind to give me the tsconfig.json and all relevant parameters to compile and lint?

**Comment by aluisiora** [comment]
Sure, you can find the tsconfig.json in the `src` folder [here](https://github.com/aluisiora/node-routeros/blob/master/src/tslint.json), and the tslint.json also in the `src` folder [here](https://github.com/aluisiora/node-routeros/blob/master/src/tsconfig.json).

If you cloned the repo, it will be already all set up. You'll need to install all dev dependencies from npm running `npm install` from the root folder, it will also install the linter and the [Typescript](https://www.typescriptlang.org/) version used. To lint it, however, I used [VSCode](https://code.visualstudio.com/) which lints as you type, you can lint manually through the command line from the root folder by:
```
./node_modules/tslint/bin/tslint -c ./src/tslint.json './src/**/*.ts'
```
And to compile you run:
```
npm run tsc:build
```
If you wanna build it everytime you save:
```
npm run tsc:build:watch
```
Like it's on the scripts of [package.json](https://github.com/aluisiora/node-routeros/blob/master/package.json).

P.S.: I looked into your PR, I tried to match it into the code so it could compile, but it didn't work though, TLS was still unstable on my end. I'll give another look into it some time soon.

**Comment by danlobo** [comment]
OK, I've put the code to work from the source, so now is compiling / linting alright.

**Comment by aluisiora** [comment]
Thanks to @danlobo , tls is now working with PR #7 .
