### ISSUE TITLE
Stream data to object

### ISSUE THREAD

**Issue by woudanator** [aluisiora/node-routeros#24]
Hi 

Been using the stream function to get tx and rx speeds of interfaces however seems like the packets i get back from the stream is not in JSON or OBJECT type what would be the best way to parse this so i can use it in my program 

what i get back is below and for some odd reason when i try and parse it i get a error 
might be me being dumb but assistance would be much appreciated 

happy to share rest of my code if needed but is just a simple stream function :-)

tried running both 

JSON.parse(packet);
JSON.parse(...packet);

error i get is 
SyntaxError: Unexpected token o in JSON at position 1

[
  {
    name: 'wlan1',
    'rx-packets-per-second': '3',   
    'rx-bits-per-second': '2016',   
    'fp-rx-packets-per-second': '3',
    'fp-rx-bits-per-second': '2016',
    'rx-drops-per-second': '0',     
    'rx-errors-per-second': '0',    
    'tx-packets-per-second': '5',   
    'tx-bits-per-second': '8880',
    'fp-tx-packets-per-second': '3',
    'fp-tx-bits-per-second': '3144',
    'tx-drops-per-second': '0',
    'tx-queue-drops-per-second': '0',
    'tx-errors-per-second': '0',
    '.section': '0'
  }
]
[
  {
    name: 'wlan1',
    'rx-packets-per-second': '4',
    'rx-bits-per-second': '2752',
    'fp-rx-packets-per-second': '4',
    'fp-rx-bits-per-second': '2752',
    'rx-drops-per-second': '0',
    'rx-errors-per-second': '0',
    'tx-packets-per-second': '6',
    'tx-bits-per-second': '10016',
    'fp-tx-packets-per-second': '3',
    'fp-tx-bits-per-second': '3184',
    'tx-drops-per-second': '0',
    'tx-queue-drops-per-second': '0',
    'tx-errors-per-second': '0',
    '.section': '1'
  }
]

**Comment by aluisiora** [comment]
Is this related to [https://github.com/aluisiora/routeros-client/issues/11](https://github.com/aluisiora/routeros-client/issues/11)?

The response you got is an array.

**Comment by woudanator** [comment]
Hi yes @aluisiora 

your solution on the routeros-client   works for both scenarios thanks :-)
