### ISSUE TITLE
Help to create a ping streaming script

### ISSUE THREAD

**Issue by bigdestroyer** [aluisiora/node-routeros#25]
I am currently writing a Telegram bot that can do the ping command (among other things) and I would like to hear if anyone can help with an example. So basically if ping count is not specified, make it 4 and ping to host at IP xxxx. If it possible to perhaps save the data after the run into min, average and max. 
Thank you for the help

**Comment by bigdestroyer** [comment]
Hi, I know this is not a issue but can someone perhaps help please

**Comment by ZackMattor** [comment]
Hello @bigdestroyer. You can just run the ping utility via the API to achieve what you're looking to do. You can setup a loop to do a bunch of them and them and store them in an array. You can then do the arithmetic to do min, max, and average using the data in an array.

https://wiki.mikrotik.com/wiki/Manual:Tools/Ping
https://www.w3schools.com/jsref/jsref_min.asp
https://www.w3schools.com/jsref/jsref_max.asp

This probably isn't the correct place to ask for non Node RouterOS programming questions :)

**Comment by aluisiora** [comment]
Closing this since it's not an issue.
