### ISSUE TITLE
its gives no such command,since its valid command in mikrotik router

### ISSUE THREAD

**Issue by bitsinside** [aluisiora/node-routeros#29]
conn.write("/interface/bridge/vlan/print/terse")

**Comment by aluisiora** [comment]
Not every command available from mikrotik's cli is available for the api part. Even though there are some available for the api (like /interface/bridge/vlan/getall I think) that you don't get using the console. 

The message you are seeing actualy came from RouterOS itself, not from this lib.

You can find out more about the mikrotik api on this link: [https://wiki.mikrotik.com/wiki/Manual:API](https://wiki.mikrotik.com/wiki/Manual:API)

**Comment by melsonmascarenhas** [comment]
@aluisiora using this command "/interface/bridge/vlan/print/terse" i want to print flags
