### ISSUE TITLE
remove by id doesn't work

### ISSUE THREAD

**Issue by scorpioRED** [aluisiora/node-routeros#9]
Hi! I can delete anything.
I got empty array ```[]``` as response for deleting actions without any error

**Comment by aluisiora** [comment]
Hi there, can you paste some sample code?

P.S.: did you follow this syntax? https://github.com/aluisiora/node-routeros/wiki/Printing,-adding,-editing-and-removing-items-and-data#removing

**Comment by scorpioRED** [comment]
Thank's! It's work with this syntax : ``` "/ip/address/remove", "=.id=*A6" ```
But with syntax as in example : ``` "/ip/address/remove", ["?.id=*A6"]  ``` it doesn't

**Comment by aluisiora** [comment]
Ok, I'll look into that, thanks.

**Comment by aluisiora** [comment]
This is a documentation issue, I'll update the README and wiki to reflect that.

**Comment by aluisiora** [comment]
Updated the readme, this is now fixed.
